### ISSUE TITLE
Insertion codes not preserved in addMissingAtoms

### ISSUE THREAD

**Issue by zhang-ivy** [pandegroup/pdbfixer#187]
This issue is related to @peastman 's fix: https://github.com/pandegroup/pdbfixer/pull/184

While `findMissingResidues` can now handle PDBs with residue insertion codes, in `addMissingAtoms` (which calls `_addAtomsToTopology`), the new topology with the missing atoms added does not maintain residue insertion codes. 

This should be a simple fix: change this line `newResidue = newTopology.addResidue(residue.name, newChain, residue.id)` (https://github.com/pandegroup/pdbfixer/blob/master/pdbfixer/pdbfixer.py#L401) 
to `newResidue = newTopology.addResidue(residue.name, newChain, residue.id, residue.insertionCode)`

**Comment by peastman** [comment]
A PR would be welcome!

**Comment by ivyzhang999** [comment]
Sorry for the delay, I'm trying to create the PR now, but I get the following error when I try to push to my newly created `insertion-codes` branch:
```remote: Permission to pandegroup/pdbfixer.git denied to ivyzhang999.
fatal: unable to access 'https://github.com/pandegroup/pdbfixer.git/': The requested URL returned error: 403```
Can you add me as a contributor to this repo?

**Comment by jchodera** [comment]
@ivyzhang999 : You should be able to [create your own fork](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) of the repo and then contribute the PO from your fork! 

We typically don't do that for projects that involve encrypted environment variables because [travis does not encrypt them in PRs from forks](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions) for security reasons, but that isn't an issue here!
